restoreSidebar();function clearFilters(){$('filterConsultant').value='';$('filterState').value='';$('filterSource').value='';loadAnalytics()}
function closeBigRanking(){$('bigRanking').classList.add('hidden')}
async function deleteSale(id){if(!confirm('Tem certeza que deseja excluir esta venda?'))return;try{await api('/api/sales/'+id,{method:'DELETE'});toast('Venda excluída.');refreshAll()}catch(e){toast(e.message)}}
function emptyRow(n){return `<tr><td colspan="${n}" class="muted">Nenhum dado no período.</td></tr>`}
async function loadAnalytics(){if(me.role!=='admin')return;try{const params=new URLSearchParams({month:$('filterMonth').value||$('month').value||monthNow()});if($('filterConsultant').value)params.set('consultant_id',$('filterConsultant').value);if($('filterState').value)params.set('state',$('filterState').value);if($('filterSource').value)params.set('lead_source_id',$('filterSource').value);const a=await api('/api/analytics?'+params.toString());$('totalLeads').textContent=a.summary.leads;$('totalConversion').textContent=pct(a.summary.conversion);renderAnalyticsTables(a);await loadFilteredSales(params)}catch(e){toast(e.message)}}
async function loadFilteredSales(params){const rows=await api('/api/sales?month='+encodeURIComponent(params.get('month')));let filtered=rows;if(params.get('consultant_id'))filtered=filtered.filter(r=>String(r.consultant_id)===String(params.get('consultant_id')));if(params.get('state'))filtered=filtered.filter(r=>r.state===params.get('state'));if(params.get('lead_source_id'))filtered=filtered.filter(r=>String(r.lead_source_id)===String(params.get('lead_source_id')));$('salesTable').innerHTML=filtered.map(s=>`<tr><td>${s.sale_date}</td><td>${esc(s.client_name)}</td><td>${esc(s.consultant_name)}</td><td>${esc(s.lead_source_name||'Origem antiga')}</td><td>${esc(s.state||'—')}</td><td class="num"><strong>${money(s.amount)}</strong></td><td class="num"><strong>${s.gross_amount==null?'—':money(s.gross_amount)}</strong></td><td class="num"><button class="btn ghost" onclick="openEditSale(${s.id})">✏️ Corrigir</button> ${me.role==='admin'?`<button class="btn danger" onclick="deleteSale(${s.id})">🗑️ Apagar</button>`:''}</td></tr>`).join('')||emptyRow(8)}

async function loadMyAnalytics(){try{const a=await api('/api/analytics?month='+encodeURIComponent($('month').value||monthNow()));$('myConversion').textContent=pct(a.summary.conversion)}catch{}}
async function loadRankingAdmins(){try{const rows=await api('/api/ranking-admins');$('rankingAdminsList').innerHTML=rows.map(u=>`<div class="admin-login-row"><div class="admin-login-name"><span class="admin-dot ${u.active?'':'off'}"></span><div><strong>${esc(u.name)}</strong><div class="muted">${esc(u.email)}</div></div></div><span class="badge ${u.active?'':'off'}">${u.active?'ADM Ranking ativo':'ADM Ranking inativo'}</span></div>`).join('')||'<div class="muted">Nenhum login ADM Ranking cadastrado.</div>'}catch(e){if($('rankingAdminsList'))$('rankingAdminsList').innerHTML='<div class="muted">Não foi possível carregar os logins ADM.</div>'}}
function openBigRanking(){if(!lastRanking.length){toast('Não há dados de ranking neste mês.');return}renderBigRanking(lastRanking);$('bigRanking').classList.remove('hidden')}
function podiumAvatar(data,name){return data?`<img class="podium-avatar" src="${data}" alt="">`:`<div class="podium-avatar">${esc((name||'?').slice(0,1).toUpperCase())}</div>`}
function renderAnalyticsTables(a){const row=(r,name)=>`<tr><td><strong>${esc(name||r.name||r.state)}</strong></td><td class="num">${r.leads}</td><td class="num">${r.sales}</td><td class="num">${pct(r.conversion)}</td><td class="num">${money(r.revenue)}</td></tr>`;$('sourceTable').innerHTML=a.bySource.map(r=>row(r,r.name)).join('')||emptyRow(5);$('stateTable').innerHTML=a.byState.map(r=>row(r,r.state)).join('')||emptyRow(5);$('consultantTable').innerHTML=a.consultants.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td class="num">${r.leads}</td><td class="num">${r.sales}</td><td class="num">${pct(r.conversion)}</td><td class="num">${money(r.revenue)}</td><td class="num">${money(r.goal)}</td><td class="num">${pct(r.goal_pct)}</td></tr>`).join('')||emptyRow(8)}
function renderBigRanking(rows){const top=rows.slice(0,3),order=[1,0,2];$('podium').innerHTML=order.map(i=>{const r=top[i];if(!r)return '';return `<div class="podium-card ${i===0?'first':''}"><div class="podium-pos">${['🥇','🥈','🥉'][i]}</div>${podiumAvatar(r.photo_data,r.name)}<div class="podium-name">${esc(r.name)}</div><div class="podium-value">${money(r.revenue)}</div><div class="podium-sales">${r.sales_count} venda(s) • ${r.goal?pct(r.goal_pct)+' da meta':'Sem meta'}</div></div>`}).join('');$('bigRest').innerHTML=rows.slice(3).map((r,i)=>`<div class="big-rest-row"><div style="font-weight:950;font-size:20px">${i+4}º</div><div class="big-rest-person">${avatar(r.photo_data,r.name)}<div style="min-width:0"><div class="name">${esc(r.name)}</div><div class="muted">${r.goal?pct(r.goal_pct)+' da meta':'Sem meta'}</div></div></div><div style="text-align:right;font-weight:950">${money(r.revenue)}</div><div style="text-align:right"><strong>${r.sales_count}</strong><div class="muted">vendas</div></div><div style="text-align:right"><strong>${money(r.avg_ticket)}</strong><div class="muted">ticket</div></div></div>`).join('')||"<div class='muted' style='padding:12px 8px'>Não há outras posições.</div>"}
function renderConsultantSummary(rank){const r=rank.find(x=>x.id===me.id)||{goal:me.goal,revenue:0,sales_count:0,goal_pct:0};$('myGoal').textContent=money(r.goal);$('myRevenue').textContent=money(r.revenue);$('myRemaining').textContent=money(Math.max(0,Number(r.goal)-Number(r.revenue)));$('myGoalPct').textContent=pct(r.goal_pct);$('mySales').textContent=r.sales_count;loadMyAnalytics()}
function renderMySales(sales){$('mySalesTable').innerHTML=sales.map(s=>`<tr><td>${s.sale_date}</td><td>${esc(s.client_name)}</td><td class="num"><strong>${money(s.amount)}</strong></td><td class="num"><strong>${s.gross_amount==null?'—':money(s.gross_amount)}</strong></td><td>${s.payment_type==='parcelado'?'Parcelado':s.payment_type==='avista'?'À vista':'—'}</td><td class="num">${s.payment_type==='parcelado'?(s.installments||'—'):'—'}</td><td><button class="btn ghost" onclick="openEditSale(${s.id})">✏️ Editar</button></td></tr>`).join('')||emptyRow(7)}
function renderRanking(rows){lastRanking=rows;const total=rows.reduce((a,r)=>a+Number(r.revenue),0),count=rows.reduce((a,r)=>a+Number(r.sales_count),0),goals=rows.reduce((a,r)=>a+Number(r.goal||0),0);if(['admin','ranking_admin'].includes(me.role)){$('totalRevenue').textContent=money(total);$('totalSales').textContent=count;$('totalGoal').textContent=money(goals);$('goal').textContent=pct(goals?total/goals*100:0)}const max=Math.max(...rows.map(r=>Number(r.revenue)),1);$('ranking').innerHTML=rows.map((r,i)=>`<div class="rank-row"><div class="pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div class="consultant">${avatar(r.photo_data,r.name)}<div style="min-width:0"><div class="name">${esc(r.name)}</div><div class="bar"><i style="width:${Math.min(100,Number(r.revenue)/max*100)}%"></i></div></div></div><div class="right"><strong>${money(r.revenue)}</strong><div class="muted">${r.goal?pct(r.goal_pct)+' da meta':'Sem meta'}</div></div><div class="right hide-md"><strong>${r.sales_count}</strong><div class="muted">vendas</div></div><div class="right hide-sm"><strong>${money(r.avg_ticket)}</strong><div class="muted">ticket</div></div></div>`).join('')||"<div class='muted'>Nenhum consultor ativo cadastrado.</div>"}
function renderRecent(sales){$('recent').innerHTML=sales.slice(0,12).map(s=>`<div class="sale"><div><strong>${esc(s.client_name)}</strong><span class="muted meta">${esc(s.consultant_name)} • ${s.sale_date} • ${esc(s.state||'—')} • ${esc(s.lead_source_name||'Origem antiga')}</span></div><span class="amount">${money(s.amount)}</span></div>`).join('')||"<div class='muted'>Nenhuma venda neste mês.</div>"}
function renderTeamRankList(elId,rows,empty){const el=$(elId);if(!el)return;const max=Math.max(...rows.map(r=>Number(r.revenue)),1);el.innerHTML=rows.map((r,i)=>`<div class="rank-row"><div class="pos">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div class="consultant">${avatar(r.photo_data,r.name)}<div style="min-width:0"><div class="name">${esc(r.name)}</div><div class="bar"><i style="width:${Math.min(100,Number(r.revenue)/max*100)}%"></i></div></div></div><div class="right"><strong>${money(r.revenue)}</strong><div class="muted">${r.goal?pct(r.goal_pct)+' da meta':'Sem meta'}</div></div><div class="right"><strong>${r.sales_count}</strong><div class="muted">vendas</div></div></div>`).join('')||`<div class='muted'>${empty}</div>`}
function renderTeamRankings(data){if(!data?.teams)return;const a=data.teams.A,b=data.teams.B;$('teamATotal').textContent=money(a.total_revenue);$('teamASales').textContent=a.total_sales;$('teamBTotal').textContent=money(b.total_revenue);$('teamBSales').textContent=b.total_sales;renderTeamRankList('teamARanking',a.rows,'Nenhum consultor ativo na Equipe A.');renderTeamRankList('teamBRanking',b.rows,'Nenhum consultor ativo na Equipe B.')}
function syncMonthAndAnalytics(){$('month').value=$('filterMonth').value;refreshAll();if(me?.role==='admin'&&$('supervisor').classList.contains('hidden')===false)loadSupervisor();if(me?.role==='admin'&&$('prizeConfig').classList.contains('hidden')===false)loadPrizeConfig()}
