
let token=localStorage.getItem('aps_token'),me=null,timer=null,usersCache=[],sourcesCache=[],photoData=null,editPhotoData=null,lastRanking=[],cardRates={};
const $=id=>document.getElementById(id);const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);const STATES=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
function avatar(photo,name){if(photo)return '<img class="avatar" src="'+photo+'" alt="">';const n=String(name||'?').trim();const initials=n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?';return '<div class="avatar">'+esc(initials)+'</div>'}
function today(){return new Date().toISOString().slice(0,10)}function monthNow(){return new Date().toISOString().slice(0,7)}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pct(v){return `${Number(v||0).toFixed(Number(v||0)%1?1:0)}%`}
function fillStates(id){$(id).innerHTML='<option value="">Selecione</option>'+STATES.map(s=>`<option value="${s}">${s}</option>`).join('')}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),Authorization:`Bearer ${token}`,'Content-Type':'application/json'};const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro');return d}
async function login(){ $('loginError').textContent='';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.token)throw new Error(d.error||('Falha no login (HTTP '+r.status+')'));token=d.token;localStorage.setItem('aps_token',token);await start()}catch(e){console.error('login',e);localStorage.removeItem('aps_token');token=null;$('loginError').textContent=e.message||'Falha no login'}}
async function loadLookups(){
  sourcesCache=await api('/api/lead-sources');
  const active=sourcesCache.filter(s=>s.active);
  const opts=active.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
  if($('saleSource')) $('saleSource').innerHTML='<option value="">Selecione</option>'+opts;
  if($('leadSource')) $('leadSource').innerHTML='<option value="">Selecione</option>'+opts;
  if($('filterSource')) $('filterSource').innerHTML='<option value="">Todas</option>'+opts;
}
async function start(){try{me=await api('/api/me');$('login').classList.add('hidden');$('app').classList.remove('hidden');const admin=me.role==='admin', rankingAdmin=me.role==='ranking_admin', privileged=admin||rankingAdmin;$('prizesNav').classList.remove('hidden');$('adminPrizeShortcut').classList.toggle('hidden',!privileged);$('supervisorNav').classList.toggle('hidden',!admin);$('teamNav').classList.toggle('hidden',!admin);$('leadsNav').classList.toggle('hidden',!admin);$('prizeConfigNav').classList.toggle('hidden',!admin);$('accountNav').classList.toggle('hidden',!admin);$('analyticsArea').classList.toggle('hidden',!admin);$('newSaleNav').classList.toggle('hidden',rankingAdmin);$('adminCards').classList.toggle('hidden',!privileged);$('consultantCards').classList.toggle('hidden',privileged);$('welcome').textContent=admin?'Administrador • visão geral da equipe':rankingAdmin?'Administrador • ranking e premiações':'Olá, '+me.name+' • seu desempenho e ranking';$('month').value=monthNow();$('filterMonth').value=monthNow();fillStates('saleState');fillStates('leadState');try{await loadCardRates()}catch(e){console.error('card rates',e)}
try{await loadLookups()}catch(e){console.error('loadLookups',e);toast('Login OK, mas não foi possível carregar as origens: '+e.message)}
try{if(admin)await loadTeam()}catch(e){console.error('loadTeam',e);toast('Login OK, mas não foi possível carregar a equipe: '+e.message)}
try{await refreshAll()}catch(e){console.error('refreshAll',e);toast('Login OK, mas não foi possível carregar os dados: '+e.message)}
clearInterval(timer);timer=setInterval(refreshAll,10000)}catch(e){console.error('start',e);logout();$('loginError').textContent=e.message||'Não foi possível iniciar a sessão'}}
function logout(){localStorage.removeItem('aps_token');token=null;clearInterval(timer);$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function toggleSidebar(){
  const sb=$('sidebar');
  const collapsed=sb.classList.toggle('collapsed');
  localStorage.setItem('apsSidebarCollapsed', collapsed?'1':'0');
  const b=$('sidebarToggle');
  if(b){b.setAttribute('aria-label',collapsed?'Expandir menu':'Recolher menu');b.title=collapsed?'Expandir menu':'Recolher menu';}
  if(typeof syncBottomHScroll==='function') syncBottomHScroll();
}
function restoreSidebar(){
  const sb=$('sidebar');
  if(!sb) return;
  if(window.innerWidth>850 && localStorage.getItem('apsSidebarCollapsed')==='1') sb.classList.add('collapsed');
}
window.addEventListener('resize',()=>{ if(window.innerWidth<=850) $('sidebar')?.classList.remove('collapsed'); });
async function refreshAll(){try{const m=$('month').value||monthNow();const [rank,sales]=await Promise.all([api('/api/ranking?month='+encodeURIComponent(m)),api('/api/sales?month='+encodeURIComponent(m))]);renderRanking(rank);renderRecent(sales);if(me?.role==='admin'){const teamData=await api('/api/team-rankings');renderTeamRankings(teamData);$('teamRankingsPanel').classList.remove('hidden');await loadAnalytics();$('consultantSalesPanel').classList.add('hidden');$('rankingAdminsPanel').classList.remove('hidden');await loadRankingAdmins();}else if(me?.role==='ranking_admin'){$('teamRankingsPanel').classList.add('hidden');$('consultantSalesPanel').classList.add('hidden');$('rankingAdminsPanel').classList.remove('hidden');await loadRankingAdmins();}else{$('teamRankingsPanel').classList.add('hidden');$('rankingAdminsPanel').classList.add('hidden');renderConsultantSummary(rank);$('consultantSalesPanel').classList.remove('hidden');renderMySales(sales)};await loadPrizes()}catch(e){if(['Sessão inválida','Não autenticado'].includes(e.message))logout();else console.error('refreshAll',e)}}
function showPage(page,btn){['dashboard','team','leads','prizes','supervisor','prizeConfig','account'].forEach(x=>$(x).classList.toggle('hidden',x!==page));document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');$('pageTitle').textContent={dashboard:'Ranking de vendas',team:'Equipe e configurações',leads:'Gestão de leads',prizes:'Premiações',supervisor:'Supervisor',prizeConfig:'Configurar premiações',account:'Minha conta'}[page]||'Ranking de vendas';if(page==='team')loadTeam();if(page==='leads')loadLeads();if(page==='prizes')loadPrizes();if(page==='supervisor'&&me.role==='admin')loadSupervisor();if(page==='prizeConfig'&&me.role==='admin')loadPrizeConfig();if(page==='account')loadAccount()}
async function loadCardRates(){cardRates=await api('/api/card-rates');['cardPlatform','esPlatform','cardPlatform2','esPlatform2'].forEach(populatePlatformSelect)}
function populatePlatformSelect(id){const el=$(id);if(!el)return;const current=el.value;el.innerHTML='<option value="">Selecione a plataforma</option>'+Object.keys(cardRates).map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(current&&cardRates[current])el.value=current}
function getCardRate(platform,n){const num=Number(n);if(!num||num<1||num>12)return null;if(num===1)return 0;const rates=cardRates&&cardRates[platform];if(!rates)return null;if(Array.isArray(rates)){const row=rates.find(x=>Number(x.installments)===num);return row&&row.rate!=null?Number(row.rate):null}if(typeof rates==='object'){const value=rates[num]??rates[String(num)];return value==null?null:Number(value)}return null}
function paymentRefs(prefix,part=1){const e=prefix==='sale'?'sale':'es';return{pay:`${e}Payment${part}`,amount:`${e}PaymentAmount${part}`,platform:`${e}Platform${part}`,inst:`${e}Installments${part}`,date:`${e}PaymentDate${part}`,platWrap:`${e}PlatformWrap${part}`,instWrap:`${e}InstallmentsWrap${part}`,sum:`${e}CardSummary${part}`}}
function readPaymentDate(prefix,part=1){const r=paymentRefs(prefix,part),el=$(r.date);if(!el)return '';let v=String(el.value||'').trim();if(!v&&el.valueAsDate instanceof Date&&!isNaN(el.valueAsDate.getTime())){const d=el.valueAsDate;v=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}if(!v){const raw=String(el.getAttribute('value')||el.dataset.date||'').trim();const m=raw.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)v=`${m[3]}-${m[2]}-${m[1]}`}return v}
function renderPaymentFields(prefix,count=1){const container=$(prefix==='sale'?'salePaymentsContainer':'esPaymentsContainer');if(!container)return;count=Math.max(1,Math.min(3,Number(count)||1));let html='';for(let i=1;i<=count;i++){html+=`<div class="payment-box"><div class="small-note"><strong>Pagamento ${String(i).padStart(2,'0')}</strong>${i>1?' <span class="muted">opcional</span>':''}</div><div class="form-grid"><div><label>Data do pagamento</label><input id="${prefix}PaymentDate${i}" type="date" onchange="this.dataset.date=this.value;recalcCard('${prefix}')" oninput="this.dataset.date=this.value;recalcCard('${prefix}')"></div><div><label>Valor</label><input id="${prefix}PaymentAmount${i}" type="number" min="0.01" step="0.01" oninput="recalcCard('${prefix}')"></div><div><label>Forma</label><select id="${prefix}Payment${i}" onchange="updateCardFields('${prefix}')"><option value="">Selecione</option><option value="avista">À vista / Pix</option><option value="parcelado">Cartão parcelado</option></select></div><div id="${prefix}PlatformWrap${i}"><label>Plataforma</label><select id="${prefix}Platform${i}" onchange="updateInstallmentOptions('${prefix}',${i});recalcCard('${prefix}')"><option value="">Selecione a plataforma</option></select></div><div id="${prefix}InstallmentsWrap${i}"><label>Parcelas</label><select id="${prefix}Installments${i}" onchange="recalcCard('${prefix}')"><option value="">Selecione</option></select></div><div id="${prefix}CardSummary${i}" class="small-note full"></div></div></div>`}container.innerHTML=html;for(let i=1;i<=count;i++){populatePlatformSelect(`${prefix}Platform${i}`)}updateCardFields(prefix)}
function updateInstallmentOptions(prefix,part=1){const r=paymentRefs(prefix,part),sel=$(r.inst);if(!sel)return;const platform=$(r.platform).value,current=Number(sel.value||0);sel.innerHTML='<option value="">Selecione</option>'+Array.from({length:12},(_,i)=>{const n=i+1,rate=getCardRate(platform,n);return `<option value="${n}" ${rate===null?'disabled':''}>${n}x${rate===null?' — indisponível':` — ${(Number(rate||0)*100).toFixed(2).replace('.',',')}%`}</option>`}).join('');if(current>=1&&current<=12&&getCardRate(platform,current)!==null)sel.value=String(current)}
function updateCardFields(prefix){const count=Number($(prefix==='sale'?'salePaymentCount':'esPaymentCount')?.value||1);for(let part=1;part<=count;part++){const r=paymentRefs(prefix,part),payment=$(r.pay);if(!payment)continue;const card=payment.value==='parcelado';$(r.platWrap).style.display=card?'block':'none';$(r.instWrap).style.display=card?'block':'none';if(card)updateInstallmentOptions(prefix,part);else{$(r.platform).value='';$(r.inst).innerHTML='<option value="">Selecione</option>';if(r.sum)$(r.sum).textContent=payment.value==='avista'?'À vista / Pix: sem desconto (0%).':''}}recalcCard(prefix)}
function recalcCard(prefix){const count=Number($(prefix==='sale'?'salePaymentCount':'esPaymentCount')?.value||1),parts=[];let grossTotal=0,netTotal=0,feeTotal=0,valid=true,maxInstallments=0;for(let i=1;i<=count;i++){const r=paymentRefs(prefix,i),amount=Number($(r.amount)?.value||0),payment=$(r.pay)?.value||'',platform=$(r.platform)?.value||'',n=Number($(r.inst)?.value||0),date=$(r.date)?.value||'';if(amount<=0){continue}if(!date||!payment){valid=false;continue}let fee=0,net=amount,rate=0;if(payment==='parcelado'){rate=getCardRate(platform,n);if(rate===null){valid=false;$(r.sum).textContent=platform&&n?`Taxa não disponível para ${platform} em ${n}x.`:'Selecione plataforma e parcelas.';continue}fee=Number((amount*Number(rate||0)).toFixed(2));net=Number((amount-fee).toFixed(2));maxInstallments=Math.max(maxInstallments,n);$(r.sum).textContent=`Taxa: ${(Number(rate||0)*100).toFixed(2).replace('.',',')}% • Desconto: ${money(fee)} • Líquido: ${money(net)}`;}else if(payment==='avista'){$(r.sum).textContent='À vista / Pix: sem desconto (0%).';}else{valid=false;continue}grossTotal+=amount;netTotal+=net;feeTotal+=fee}if(valid&&grossTotal>0){$(prefix==='sale'?'amount':'esAmount').value=netTotal.toFixed(2);$(prefix==='sale'?'totalSummary':'esTotalSummary').textContent=`Total bruto: ${money(grossTotal)} • Desconto total: ${money(feeTotal)} • Líquido no ranking: ${money(netTotal)}${count>1?' • '+String(count).padStart(2,'0')+' pagamentos':''}${maxInstallments?' • Premiação: '+maxInstallments+'x':''}`;}else{$(prefix==='sale'?'amount':'esAmount').value='';$(prefix==='sale'?'totalSummary':'esTotalSummary').textContent='';}}
async function openEditSale(id){const rows=await api('/api/sales?month='+encodeURIComponent($('month').value||monthNow()));const s=rows.find(x=>x.id===id);if(!s)return;if(me.role==='ranking_admin')return toast('Este acesso não pode editar vendas');if(me.role==='admin')usersCache=await api('/api/users');$('esId').value=s.id;$('esClient').value=s.client_name;$('esBirthDate').value=s.birth_date||'';const count=s.payment_amount_3>0?3:(s.payment_amount_2>0?2:1);$('esPaymentCount').value=String(count);renderPaymentFields('es',count);for(let i=1;i<=count;i++){const suf=i===1?'':'_'+i;$(paymentRefs('es',i).amount).value=i===1?(Number(s.gross_amount||0)-Number(s.payment_amount_2||0)-Number(s.payment_amount_3||0)):Number(s[`payment_amount${suf}`]||0);$(paymentRefs('es',i).pay).value=s[`payment_type${suf}`]||'';$(paymentRefs('es',i).date).value=s[`payment_date${suf}`]||s.sale_date||'';$(paymentRefs('es',i).platform).value=s[`card_platform${suf}`]||'';updateInstallmentOptions('es',i);$(paymentRefs('es',i).inst).value=s[`installments${suf}`]||''}updateCardFields('es');fillStates('esState');$('esState').value=s.state||'';const cs=me.role==='admin'?usersCache.filter(u=>u.role==='consultant'):[];$('esConsultant').innerHTML=me.role==='admin'?cs.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join():`<option value="${me.id}">${esc(me.name)}</option>`;$('esConsultant').value=s.consultant_id;$('esConsultant').disabled=me.role!=='admin';$('esSource').innerHTML=sourcesCache.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('esSource').value=s.lead_source_id||'';$('editSaleModal').classList.remove('hidden')}
function markMissing(prefix, ids){
  document.querySelectorAll('.input-error').forEach(el=>el.classList.remove('input-error'));
  ids.forEach(id=>$(id)?.classList.add('input-error'));
  if(ids[0]) $(ids[0])?.focus();
}
function validateSaleForm(prefix){
  const missing=[], ids=[], count=Number($(prefix==='sale'?'salePaymentCount':'esPaymentCount')?.value||1);
  const base=prefix==='sale'?{client:'client',birth:'clientBirthDate',state:'saleState',source:'saleSource',consultant:'saleConsultant'}:{client:'esClient',birth:'esBirthDate',state:'esState',source:'esSource',consultant:'esConsultant'};
  const add=(label,id)=>{if(!missing.includes(label))missing.push(label);if(id&&!ids.includes(id))ids.push(id)};
  if(!$(base.client)?.value.trim()) add('Cliente',base.client);
  if(!$(base.birth)?.value) add('Data de nascimento',base.birth);
  else { const bd=new Date($(base.birth).value+'T00:00:00'); const now=new Date(); let age=now.getFullYear()-bd.getFullYear(); const md=now.getMonth()-bd.getMonth(); if(md<0||(md===0&&now.getDate()<bd.getDate()))age--; if(!Number.isFinite(age)||age<18||age>120)add('Data de nascimento válida (18+)',base.birth); }
  if(!$(base.state)?.value) add('Estado',base.state);
  if(!$(base.source)?.value) add('Origem do lead',base.source);
  if(prefix==='sale'&&me?.role==='admin'&&!Number($(base.consultant)?.value||0)) add('Consultor',base.consultant);
  for(let i=1;i<=count;i++){
    const r=paymentRefs(prefix,i), label=`Pagamento ${String(i).padStart(2,'0')}`;
    const amount=Number($(r.amount)?.value||0), form=$(r.pay)?.value||'', date=readPaymentDate(prefix,i);
    if(amount<=0) add(`${label}: valor`,r.amount);
    if(!date) add(`${label}: data`,r.date);
    if(!form) add(`${label}: forma de pagamento`,r.pay);
    if(form==='parcelado'){
      if(!$(r.platform)?.value) add(`${label}: plataforma`,r.platform);
      if(!$(r.inst)?.value) add(`${label}: parcelas`,r.inst);
    }
  }
  markMissing(prefix,ids);
  return missing;
}
async function saveEditSale(){try{const missing=validateSaleForm('es');if(missing.length){toast('Falta preencher: '+missing.join(', '));return;}const count=Number($('esPaymentCount').value||1),payload={client_name:$('esClient').value.trim(),birth_date:$('esBirthDate').value,state:$('esState').value,lead_source_id:Number($('esSource').value),consultant_id:Number($('esConsultant').value)};for(let i=1;i<=count;i++){const r=paymentRefs('es',i),suf=i===1?'':'_'+i,date=readPaymentDate('es',i);payload[`payment_amount${i===1?'_1':suf}`]=$(r.amount).value;payload[`payment_type${i===1?'_1':suf}`]=$(r.pay).value;payload[`installments${i===1?'_1':suf}`]=$(r.inst).value?Number($(r.inst).value):null;payload[`card_platform${i===1?'_1':suf}`]=$(r.platform).value||null;payload[`payment_date${i===1?'_1':suf}`]=date}await api('/api/sales/'+$('esId').value,{method:'PATCH',body:JSON.stringify(payload)});closeModal('editSaleModal');toast('Venda corrigida!');refreshAll()}catch(e){toast(e.message)}}
async function saveSale(){try{const missing=validateSaleForm('sale');if(missing.length){toast('Falta preencher: '+missing.join(', '));return;}const count=Number($('salePaymentCount').value||1),payload={client_name:$('client').value.trim(),birth_date:$('clientBirthDate').value,state:$('saleState').value,lead_source_id:Number($('saleSource').value)};for(let i=1;i<=count;i++){const r=paymentRefs('sale',i),suf=i===1?'':'_'+i;payload[`payment_amount${suf}`]=$(r.amount).value;payload[`payment_type${suf}`]=$(r.pay).value;payload[`installments${suf}`]=$(r.inst).value?Number($(r.inst).value):null;payload[`card_platform${suf}`]=$(r.platform).value||null;payload[`payment_date${suf}`]=$(r.date).value}if(me.role==='admin')payload.consultant_id=Number($('saleConsultant').value);await api('/api/sales',{method:'POST',body:JSON.stringify(payload)});closeModal('saleModal');toast('Venda registrada!');refreshAll()}catch(e){toast(e.message)}}
let newUserRole='consultant';
function openUser(role='consultant'){newUserRole=role;photoData=null;$('uPhoto').value='';$('uPreview').removeAttribute('src');['uName','uEmail','uPassword','uGoal'].forEach(x=>$(x).value='');$('uTeam').value='A';$('userModalTitle').textContent=role==='ranking_admin'?'Novo login ADM Ranking':'Novo consultor';$('uGoalWrap').classList.toggle('hidden',role==='ranking_admin');$('uTeamWrap').classList.toggle('hidden',role==='ranking_admin');$('userModal').classList.remove('hidden');$('uName').focus()}
async function saveUser(){try{await api('/api/users',{method:'POST',body:JSON.stringify({name:$('uName').value,email:$('uEmail').value,password:$('uPassword').value,goal:$('uGoal').value,photo_data:photoData,role:newUserRole,team:$('uTeam').value})});closeModal('userModal');toast(newUserRole==='ranking_admin'?'Login ADM Ranking cadastrado!':'Consultor cadastrado!');await loadTeam();await loadLookups();refreshAll()}catch(e){toast(e.message)}}
async function loadTeam(){if(me.role!=='admin')return;try{usersCache=await api('/api/users');const cs=usersCache.filter(u=>u.role==='consultant');const ras=usersCache.filter(u=>u.role==='ranking_admin');$('filterConsultant').innerHTML='<option value="">Todos</option>'+cs.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('');const consultantCards=cs.map(u=>`<div class="team-card">${u.photo_data?`<img src="${u.photo_data}" alt="">`:avatar(null,u.name)}<div><strong>${esc(u.name)}</strong><div class="muted">${esc(u.email)} • Meta ${money(u.goal)} • <strong>Equipe ${esc(u.team||'A')}</strong></div><span class="badge ${u.active?'':'off'}">${u.active?'Consultor ativo':'Consultor inativo'}</span></div><button class="btn ghost" onclick="openEditUser(${u.id})">Editar</button></div>`).join('');const rankingAdminCards=ras.map(u=>`<div class="team-card">${u.photo_data?`<img src="${u.photo_data}" alt="">`:avatar(null,u.name)}<div><strong>${esc(u.name)}</strong><div class="muted">${esc(u.email)}</div><span class="badge ${u.active?'':'off'}">${u.active?'ADM Ranking ativo':'ADM Ranking inativo'}</span></div><button class="btn ghost" onclick="openEditUser(${u.id})">Editar</button></div>`).join('');$('teamList').innerHTML=(consultantCards||"")+(rankingAdminCards?`<div class="small-note" style="margin:16px 0 8px"><strong>Logins ADM Ranking</strong></div>${rankingAdminCards}`:'')||"<div class='muted'>Nenhum usuário cadastrado.</div>";await loadSources()}catch(e){toast(e.message)}}
function openEditUser(id){const u=usersCache.find(x=>x.id===id);if(!u)return;editPhotoData=u.photo_data||null;$('eId').value=u.id;$('eName').value=u.name;$('eEmail').value=u.email;$('eGoal').value=u.goal;$('ePassword').value='';$('eActive').value=u.active?'1':'0';$('eTeam').value=u.team||'A';if(editPhotoData)$('ePreview').src=editPhotoData;else $('ePreview').removeAttribute('src');$('ePhoto').value='';$('editModal').classList.remove('hidden')}
async function saveEditUser(){try{await api('/api/users/'+$('eId').value,{method:'PATCH',body:JSON.stringify({name:$('eName').value,email:$('eEmail').value,goal:$('eGoal').value,password:$('ePassword').value,active:$('eActive').value==='1',photo_data:editPhotoData,team:$('eTeam').value})});closeModal('editModal');toast('Consultor atualizado!');await loadTeam();refreshAll()}catch(e){toast(e.message)}}
async function loadSources(){sourcesCache=await api('/api/lead-sources');$('sourceList').innerHTML=sourcesCache.map(s=>`<div class="source-row"><div><strong>${esc(s.name)}</strong><div class="muted">${s.active?'Disponível para novos lançamentos':'Inativa'}</div></div><button class="btn ghost" onclick="editSource(${s.id})">${s.active?'Desativar':'Ativar'}</button></div>`).join('')}
async function addSource(){const name=prompt('Nome da nova origem:');if(!name)return;try{await api('/api/lead-sources',{method:'POST',body:JSON.stringify({name})});toast('Origem cadastrada!');await loadLookups();loadSources()}catch(e){toast(e.message)}}
async function editSource(id){const s=sourcesCache.find(x=>x.id===id);if(!s)return;const name=prompt('Nome da origem:',s.name);if(name===null)return;const active=!s.active;try{await api('/api/lead-sources/'+id,{method:'PATCH',body:JSON.stringify({name:name.trim()||s.name,active})});toast(active?'Origem ativada!':'Origem desativada!');await loadLookups();loadSources()}catch(e){toast(e.message)}}
function openLead(){if(me.role!=='admin')return;usersCache=usersCache.length?usersCache:[];$('leadDate').value=today();$('leadQty').value='';$('leadConsultant').innerHTML=usersCache.filter(u=>u.role==='consultant'&&u.active).map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('');$('leadSource').value='';$('leadState').value='';$('leadModal').classList.remove('hidden')}
async function saveLead(){try{await api('/api/leads',{method:'POST',body:JSON.stringify({lead_date:$('leadDate').value,quantity:$('leadQty').value,consultant_id:Number($('leadConsultant').value),lead_source_id:Number($('leadSource').value),state:$('leadState').value})});closeModal('leadModal');toast('Leads registrados!');loadLeads();refreshAll()}catch(e){toast(e.message)}}
async function loadLeads(){if(me.role!=='admin')return;try{const rows=await api('/api/leads?month='+encodeURIComponent($('month').value||monthNow()));$('leadsTable').innerHTML=rows.map(r=>`<tr><td>${r.lead_date}</td><td>${esc(r.consultant_name)}</td><td>${esc(r.lead_source_name)}</td><td>${esc(r.state)}</td><td class="num"><strong>${r.quantity}</strong></td><td class="num"><button class="btn ghost" onclick="openEditLead(${r.id})">✏️ Corrigir</button> <button class="btn danger" onclick="deleteLead(${r.id})">🗑️ Apagar</button></td></tr>`).join('')||emptyRow(6)}catch(e){toast(e.message)}}
async function deleteLead(id){if(!confirm('Tem certeza que deseja excluir este registro de leads?'))return;try{await api('/api/leads/'+id,{method:'DELETE'});toast('Registro de leads excluído.');loadLeads();refreshAll()}catch(e){toast(e.message)}}
async function openEditLead(id){const rows=await api('/api/leads?month='+encodeURIComponent($('month').value||monthNow()));const r=rows.find(x=>x.id===id);if(!r)return;usersCache=usersCache.length?usersCache:await api('/api/users');$('elId').value=r.id;$('elDate').value=r.lead_date;$('elQty').value=r.quantity;fillStates('elState');$('elState').value=r.state||'';const cs=usersCache.filter(u=>u.role==='consultant');$('elConsultant').innerHTML=cs.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('');$('elConsultant').value=r.consultant_id;$('elSource').innerHTML=sourcesCache.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('elSource').value=r.lead_source_id;$('editLeadModal').classList.remove('hidden')}
async function saveEditLead(){try{await api('/api/leads/'+$('elId').value,{method:'PATCH',body:JSON.stringify({lead_date:$('elDate').value,quantity:$('elQty').value,consultant_id:Number($('elConsultant').value),lead_source_id:Number($('elSource').value),state:$('elState').value})});closeModal('editLeadModal');toast('Leads corrigidos!');loadLeads();refreshAll()}catch(e){toast(e.message)}}
async function loadAccount(){if(me.role!=='admin')return;me=await api('/api/me');$('adminName').value=me.name;$('adminEmail').value=me.email;$('adminPassword').value=''}
async function saveAccount(){try{await api('/api/me',{method:'PATCH',body:JSON.stringify({email:$('adminEmail').value,new_password:$('adminPassword').value})});me=await api('/api/me');$('adminPassword').value='';toast('Conta atualizada.')}catch(e){toast(e.message)}}

function toggleInstallments(typeId,installId){const p=$(typeId).value;$(installId).parentElement.style.display=p==='parcelado'?'block':'none';if(p!=='parcelado')$(installId).value=''}
function money2(v){return money(v)}
async function loadPrizes(){
  try{
    const m=$('month').value||monthNow();const d=await api('/api/prizes?month='+encodeURIComponent(m));
    const privileged=['admin','ranking_admin'].includes(me.role);const mine=privileged?null:d.consultants[0];const consultantTotal=d.consultants.reduce((a,c)=>a+Number(c.total_prize),0);
    if(privileged){
      let supervisorTotal=0;
      try{const sup=await api('/api/supervisor-prizes?month='+encodeURIComponent(m));supervisorTotal=Number(sup.total_prize||0)}catch(e){supervisorTotal=0}
      const total=consultantTotal+supervisorTotal;
      $('prizeHeadAdmin').innerHTML='<th>Consultor</th><th>Faturamento bruto</th><th>Prêmios</th><th>Total</th><th>Detalhes</th>';
      $('prizeTotal').textContent=money(total);$('prizeCount').textContent=d.consultants.reduce((a,c)=>a+c.awards.length,0);$('prizeRevenue').textContent=money(d.consultants.reduce((a,c)=>a+Number(c.gross_revenue||0),0));$('adminPrizeHeader').classList.remove('hidden');if($('adminPrizeTotal'))$('adminPrizeTotal').textContent=money(total);if($('adminPrizeCount'))$('adminPrizeCount').textContent=d.consultants.reduce((a,c)=>a+c.awards.length,0);if($('adminPrizeGross'))$('adminPrizeGross').textContent=money(d.consultants.reduce((a,c)=>a+Number(c.gross_revenue||0),0));
      $('prizeTable').innerHTML=d.consultants.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${money(c.gross_revenue||0)}</td><td>${c.awards.length}</td><td><strong>${money(c.total_prize)}</strong></td><td>${c.awards.slice(0,6).map(a=>`<div style="margin-bottom:6px"><span class="prize-pill">${money(a.amount)}</span> ${esc(a.rule_name)}<div class="small-note">${esc(a.reason)} • ${a.date}</div></div>`).join('')||'<span class="muted">Nenhum prêmio no mês</span>'}</td></tr>`).join('')||emptyRow(5);
      $('myPrizeHistory').innerHTML=`<div class="muted">Consultoras: ${money(consultantTotal)} • Supervisor: ${money(supervisorTotal)} • <strong>Total geral: ${money(total)}</strong></div>`;await loadLosses();if(me.role==='ranking_admin')await loadLimitedSupervisor();
    }else{
      $('prizeTotal').textContent=money(mine?.total_prize||0);$('prizeCount').textContent=mine?.awards.length||0;$('prizeRevenue').textContent=money(mine?.gross_revenue||0);$('adminPrizeHeader').classList.add('hidden');
      $('prizeHeadAdmin').innerHTML='<th>Data</th><th>Premiação</th><th>Valor</th>';
      $('prizeTable').innerHTML=mine?.awards.map(a=>`<tr><td>${a.date}</td><td><strong>${esc(a.rule_name)}</strong><div class="small-note">${esc(a.reason)}</div></td><td>${money(a.amount)}</td></tr>`).join('')||'<tr><td colspan="3" class="muted">Nenhuma premiação neste mês.</td></tr>';
      $('consultantPrizeTeam').classList.remove('hidden');$('consultantPrizeTeamTable').innerHTML=d.consultants.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${c.awards.length}</td><td><strong>${money(c.total_prize)}</strong></td></tr>`).join('')||emptyRow(3);
      $('myPrizeHistory').innerHTML=mine?.awards.map(a=>`<div class="sale"><div><strong>${esc(a.rule_name)}</strong><span class="muted meta">${a.date} • ${esc(a.reason)}</span></div><span class="amount">${money(a.amount)}</span></div>`).join('')||'<div class="muted">Nenhuma premiação.</div>';
      $('myPrizeLosses').innerHTML='<div class="muted">Os motivos de perda são administrados pelo supervisor.</div>';
      const rules=await api('/api/prize-rules');$('consultantPrizeRules').classList.remove('hidden');$('consultantPrizeRulesTable').innerHTML=rules.filter(r=>r.active).map(r=>{const cond=r.category==='sale'?`${money(r.min_amount||0)}${r.max_installments?` • ${r.min_installments&&r.min_installments!==r.max_installments?r.min_installments+' a '+r.max_installments:r.max_installments}x`:''}${r.payment_type?` • ${r.payment_type==='avista'?'À vista':'Parcelado'}`:''}`:r.category==='daily'?`Acumulado diário a partir de ${money(r.min_amount||0)} (mín. 2 vendas)`:r.category==='weekly'?`Acumulado semanal a partir de ${money(r.min_amount||0)} (mín. 2 vendas)`:r.category==='daily_rank'?'Meta da equipe: R$ 7.500 no dia':r.category==='all_days'?'Venda em todos os dias úteis da semana':money(r.min_amount||0);return `<tr><td><strong>${esc(r.name)}</strong></td><td>${esc(cond)}</td><td><strong>${money(r.prize_amount)}</strong></td></tr>`}).join('')||emptyRow(3);
    }
  }catch(e){toast(e.message)}
}
async function loadPrizeConfig(){
  if(me.role!=='admin')return;
  try{const rules=await api('/api/prize-rules');$('rulesList').innerHTML=rules.map(r=>`<div class="rule-row"><div><strong>${esc(r.name)}</strong><div class="small-note">${esc(r.description||'')}</div></div><div>${money(r.min_amount)} ${r.max_installments?`• ${r.min_installments&&r.min_installments!==r.max_installments?r.min_installments+'-'+r.max_installments:r.max_installments}x`:''}</div><div><strong>${money(r.prize_amount)}</strong></div><div><span class="badge ${r.active?'':'off'}">${r.active?'Ativa':'Inativa'}</span></div><div><button class="btn ghost" onclick="editPrizeRule(${r.id})">Editar</button></div></div>`).join('')||'<div class="muted">Nenhuma regra.</div>';usersCache=await api('/api/users');$('lossConsultant').innerHTML=usersCache.filter(u=>u.role==='consultant').map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('');$('lossDate').value=today();await loadLosses()}catch(e){toast(e.message)}
}
async function addPrizeRule(){
 const name=prompt('Nome da regra:');if(!name)return;const prize=prompt('Valor da premiação (R$):','0');if(prize===null)return;const min=prompt('Valor mínimo da condição (R$):','0');if(min===null)return;
 const category=prompt('Categoria: sale, daily, weekly, all_days, daily_rank ou dynamic','dynamic');if(!category)return;
 const payment=category==='sale'?prompt('Pagamento: avista ou parcelado','parcelado'):null;const max=category==='sale'?prompt('Máximo de parcelas (ex.: 6, 7, 8). Deixe vazio para à vista',''):null;const minInst=category==='sale'&&max?prompt('Mínimo de parcelas (para ATÉ 6x use 2)','2'):null;
 try{await api('/api/prize-rules',{method:'POST',body:JSON.stringify({name,prize_amount:Number(prize),min_amount:Number(min),category,payment_type:payment||null,max_installments:max?Number(max):null,min_installments:minInst?Number(minInst):null})});toast('Regra adicionada.');loadPrizeConfig();loadPrizes()}catch(e){toast(e.message)}
}
async function editPrizeRule(id){
 const rules=await api('/api/prize-rules');const r=rules.find(x=>x.id===id);if(!r)return;
 const prize=prompt('Valor da premiação (R$):',r.prize_amount);if(prize===null)return;const active=confirm('Clique OK para deixar a regra ATIVA. Cancelar = INATIVA.');
 try{await api('/api/prize-rules/'+id,{method:'PATCH',body:JSON.stringify({prize_amount:Number(prize),active})});toast('Regra atualizada.');loadPrizeConfig();loadPrizes()}catch(e){toast(e.message)}
}
async function loadLosses(){if(!['admin','ranking_admin'].includes(me.role))return;try{const rows=await api('/api/prize-losses?month='+encodeURIComponent($('month').value||monthNow()));if($('lossTable'))$('lossTable').innerHTML=rows.map(r=>`<tr><td>${r.loss_date}</td><td>${esc(r.consultant_name)}</td><td>${esc(r.reason)}</td><td>${esc(r.notes||'—')}</td><td>${me.role==='admin'?`<button class="btn danger" onclick="deleteLoss(${r.id})">Apagar</button>`:'Somente visualização'}</td></tr>`).join('')||emptyRow(5);$('myPrizeLosses').innerHTML=rows.map(r=>`<div class="sale"><div><strong>${esc(r.consultant_name)} — ${esc(r.reason)}</strong><span class="muted meta">${r.loss_date}${r.notes?' • '+esc(r.notes):''}</span></div></div>`).join('')||'<div class="muted">Nenhum motivo de perda registrado neste mês.</div>'}catch(e){toast(e.message)}}
async function loadLimitedSupervisor(){try{const d=await api('/api/supervisor-prizes?month='+encodeURIComponent($('month').value||monthNow()));const s=d.settings;$('limitedSupervisor').classList.remove('hidden');$('limitedSupDailyGoal').textContent=money(s.daily_goal?.value||0);$('limitedSupDailyPrize').textContent=money(s.daily_prize?.value||0);$('limitedSupWeeklyGoal').textContent=money(s.weekly_goal?.value||0);$('limitedSupWeeklyPrize').textContent=money(s.weekly_prize?.value||0);$('limitedSupTotalPrize').textContent=money(d.total_prize||0);$('limitedSupDailyTable').innerHTML=d.daily.map(x=>`<tr><td>${x.sale_date}</td><td>${money(x.revenue)}</td><td>${x.hit?'Meta batida':'Não batida'}</td><td>${x.multiplier>1?x.multiplier+'x • ':''}${money(x.prize)}</td></tr>`).join('')||emptyRow(4);$('limitedSupWeeklyTable').innerHTML=d.weekly.map(x=>`<tr><td>${x.week_start}</td><td>${money(x.revenue)}</td><td>${x.hit?'Meta batida':'Não batida'}</td><td>${x.multiplier>1?x.multiplier+'x • ':''}${money(x.prize)}</td></tr>`).join('')||emptyRow(4)}catch(e){toast(e.message)}}
async function savePrizeLoss(){try{await api('/api/prize-losses',{method:'POST',body:JSON.stringify({consultant_id:Number($('lossConsultant').value),loss_date:$('lossDate').value,period_month:($('lossDate').value||today()).slice(0,7),reason:$('lossReason').value,notes:$('lossNotes').value})});$('lossReason').value='';$('lossNotes').value='';toast('Perda registrada.');loadLosses();loadPrizes()}catch(e){toast(e.message)}}
async function deleteLoss(id){if(!confirm('Apagar este registro de perda?'))return;try{await api('/api/prize-losses/'+id,{method:'DELETE'});toast('Registro apagado.');loadLosses();loadPrizes()}catch(e){toast(e.message)}}
async function loadSupervisor(){if(me.role!=='admin')return;try{const d=await api('/api/supervisor-prizes?month='+encodeURIComponent($('month').value||monthNow()));const s=d.settings;$('supDailyGoal').textContent=money(s.daily_goal?.value||0);$('supDailyPrize').textContent=money(s.daily_prize?.value||0);$('supWeeklyGoal').textContent=money(s.weekly_goal?.value||0);$('supWeeklyPrize').textContent=money(s.weekly_prize?.value||0);$('supTotalDailyPrize').textContent=money(d.total_daily_prize||0);$('supTotalWeeklyPrize').textContent=money(d.total_weekly_prize||0);$('supTotalPrize').textContent=money(d.total_prize||0);$('cfgDailyGoal').value=s.daily_goal?.value||0;$('cfgDailyPrize').value=s.daily_prize?.value||0;$('cfgWeeklyGoal').value=s.weekly_goal?.value||0;$('cfgWeeklyPrize').value=s.weekly_prize?.value||0;$('supDailyTable').innerHTML=d.daily.map(x=>`<tr><td>${x.sale_date}</td><td>${money(x.revenue)}</td><td>${x.hit?'<span class="prize-pill">Meta batida</span>':'<span class="prize-pill prize-lost">Não batida</span>'}</td><td>${x.multiplier>1?x.multiplier+'x • ':''}${money(x.prize)}</td></tr>`).join('')||emptyRow(4);$('supWeeklyTable').innerHTML=d.weekly.map(x=>`<tr><td>${x.week_start}</td><td>${money(x.revenue)}</td><td>${x.hit?'<span class="prize-pill">Meta batida</span>':'<span class="prize-pill prize-lost">Não batida</span>'}</td><td>${x.multiplier>1?x.multiplier+'x • ':''}${money(x.prize)}</td></tr>`).join('')||emptyRow(4)}catch(e){toast(e.message)}}
async function saveSupervisorConfig(){for(const [n,id] of [['daily_goal','cfgDailyGoal'],['daily_prize','cfgDailyPrize'],['weekly_goal','cfgWeeklyGoal'],['weekly_prize','cfgWeeklyPrize']]){try{await api('/api/supervisor-prizes/'+n,{method:'PATCH',body:JSON.stringify({value:Number($(id).value)})})}catch(e){toast(e.message);return}}toast('Configurações salvas.');loadSupervisor();loadPrizes()}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',2800)}
if(token)start();

function updateHorizontalScrollHint(){
  const bar=document.getElementById('bottomHScroll');
  const inner=document.getElementById('bottomHScrollInner');
  const main=document.querySelector('.main');
  if(!bar||!inner||!main)return;
  if(window.innerWidth<=850){bar.style.display='none';return}
  bar.style.display='block';
  const contentWidth=Math.max(main.scrollWidth,2200);
  inner.style.width=contentWidth+'px';
  const maxBar=Math.max(0,bar.scrollWidth-bar.clientWidth);
  const maxMain=Math.max(0,main.scrollWidth-main.clientWidth);
  const ratio=maxBar/(maxMain||1);
  const target=maxMain?main.scrollLeft*ratio:0;
  if(Math.abs(bar.scrollLeft-target)>1)bar.scrollLeft=target;
}
(function setupBottomHorizontalScroll(){
  const bar=document.getElementById('bottomHScroll');
  const main=document.querySelector('.main');
  if(!bar||!main)return;
  let syncing=false;
  bar.addEventListener('scroll',()=>{
    if(syncing)return;
    syncing=true;
    const maxBar=Math.max(0,bar.scrollWidth-bar.clientWidth);
    const maxMain=Math.max(0,main.scrollWidth-main.clientWidth);
    main.scrollLeft=maxBar?bar.scrollLeft/maxBar*maxMain:0;
    syncing=false;
  },{passive:true});
  main.addEventListener('scroll',()=>{
    if(syncing)return;
    syncing=true;
    const maxBar=Math.max(0,bar.scrollWidth-bar.clientWidth);
    const maxMain=Math.max(0,main.scrollWidth-main.clientWidth);
    bar.scrollLeft=maxMain?main.scrollLeft/maxMain*maxBar:0;
    syncing=false;
  },{passive:true});
  window.addEventListener('resize',()=>setTimeout(updateHorizontalScrollHint,0));
  window.addEventListener('load',()=>{
    document.documentElement.scrollLeft=0;document.body.scrollLeft=0;main.scrollLeft=0;bar.scrollLeft=0;updateHorizontalScrollHint();
  });
  setTimeout(()=>{main.scrollLeft=0;bar.scrollLeft=0;updateHorizontalScrollHint()},100);
  setTimeout(updateHorizontalScrollHint,500);
  setTimeout(updateHorizontalScrollHint,1500);
})();
