import { httpServerHandler } from "cloudflare:node";

let runtimeState = globalThis.__APS_RANKING_RUNTIME || {
  loaded: false,
  app: null,
  expressHandler: null,
  initPromise: null,
};
globalThis.__APS_RANKING_RUNTIME = runtimeState;

function base64url(value) {
  const bytes = typeof value === "string" ? new TextEncoder().encode(value) : new Uint8Array(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

async function signJwt(payload, secret) {
  const header = base64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const body = base64url(JSON.stringify({ ...payload, iat: Math.floor(Date.now() / 1000), exp: Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60 }));
  const data = `${header}.${body}`;
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(data));
  return `${data}.${base64url(signature)}`;
}

async function loginDirect(request, workerEnv) {
  const body = await request.json();
  const email = String(body?.email || "").trim().toLowerCase();
  const password = String(body?.password || "");

  if (!email || !password) {
    return Response.json({ error: "Informe e-mail e senha" }, { status: 400 });
  }

  const connectionString = workerEnv.HYPERDRIVE?.connectionString;
  if (!connectionString) {
    console.error("Login: Hyperdrive sem connectionString");
    return Response.json({ error: "Banco de dados não conectado" }, { status: 500 });
  }

  const { Client } = await import("pg");
  const { default: bcrypt } = await import("bcryptjs");
  const client = new Client({ connectionString });
  try {
    await client.connect();

    // Login must work even before the full Express runtime has been initialized.
    // Create the minimal users table here and provision the configured/default admin.
    await client.query(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'consultant',
        active INTEGER NOT NULL DEFAULT 1,
        goal REAL NOT NULL DEFAULT 0,
        photo_data TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);

    let result = await client.query(
      "SELECT id, name, email, password_hash, role, goal, photo_data FROM users WHERE email=$1 AND active=1 LIMIT 1",
      [email]
    );

    // If this is a fresh PostgreSQL database, create the initial admin using
    // the same variables used by the full application.
    if (!result.rows[0]) {
      const adminEmail = String(workerEnv.ADMIN_EMAIL || "admin@aps.local").trim().toLowerCase();
      const adminPassword = String(workerEnv.ADMIN_PASSWORD || "123456");
      const existingAdmin = await client.query(
        "SELECT id FROM users WHERE role='admin' ORDER BY id LIMIT 1"
      );
      if (!existingAdmin.rows[0] && email === adminEmail && password === adminPassword) {
        const hash = await bcrypt.hash(adminPassword, 10);
        await client.query(
          "INSERT INTO users (name,email,password_hash,role,goal,active) VALUES ($1,$2,$3,'admin',0,1)",
          ["Administrador", adminEmail, hash]
        );
        result = await client.query(
          "SELECT id, name, email, password_hash, role, goal, photo_data FROM users WHERE email=$1 AND active=1 LIMIT 1",
          [email]
        );
      }
    }
    const user = result.rows[0];

    if (!user || !(await bcrypt.compare(password, user.password_hash))) {
      return Response.json({ error: "E-mail ou senha inválidos" }, { status: 401 });
    }

    const secret = workerEnv.JWT_SECRET || "TROQUE-ESTE-SEGREDO-EM-PRODUCAO";
    const token = await signJwt(
      { id: user.id, name: user.name, email: user.email, role: user.role },
      secret
    );

    return Response.json({
      token,
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role,
        goal: user.goal,
        photo_data: user.photo_data || null,
      },
    });
  } catch (error) {
    console.error("Falha no login via Hyperdrive:", error);
    return Response.json({ error: "Erro interno ao realizar login" }, { status: 500 });
  } finally {
    await client.end().catch(() => {});
  }
}

async function getRuntime(workerEnv) {
  if (!runtimeState.loaded) {
    if (!workerEnv.HYPERDRIVE?.connectionString) {
      throw new Error("HYPERDRIVE não configurado.");
    }

    globalThis.__CF_ENV = {
      CF_WORKER: "1",
      DATABASE_URL: workerEnv.HYPERDRIVE.connectionString,
      JWT_SECRET: workerEnv.JWT_SECRET,
      ADMIN_EMAIL: workerEnv.ADMIN_EMAIL,
      ADMIN_PASSWORD: workerEnv.ADMIN_PASSWORD,
      PRIZE_START_DATE: workerEnv.PRIZE_START_DATE,
      TEAM_B_PRIZE_START_DATE: workerEnv.TEAM_B_PRIZE_START_DATE,
      SUPERVISOR_ALL_TEAMS_START_DATE: workerEnv.SUPERVISOR_ALL_TEAMS_START_DATE,
    };

    const { app, init } = await import("./server.js");
    app.listen(3000);
    runtimeState.app = app;
    runtimeState.expressHandler = httpServerHandler({ port: 3000 });
    runtimeState.init = init;
    runtimeState.loaded = true;
  }
  return runtimeState;
}

async function ensureDatabase(state) {
  if (!state.initPromise) {
    state.initPromise = state.init().catch((error) => {
      state.initPromise = null;
      throw error;
    });
  }
  return state.initPromise;
}

export default {
  async fetch(request, workerEnv, ctx) {
    const url = new URL(request.url);

    if (!url.pathname.startsWith("/api/")) {
      return workerEnv.ASSETS.fetch(request);
    }

    if (url.pathname === "/api/health" && request.method === "GET") {
      const connectionString = workerEnv.HYPERDRIVE?.connectionString;
      if (!connectionString) return Response.json({ ok: false, error: "HYPERDRIVE não configurado" }, { status: 500 });
      try {
        const { Client } = await import("pg");
        const client = new Client({ connectionString });
        await client.connect();
        const result = await client.query("SELECT 1 AS ok");
        await client.end().catch(() => {});
        return Response.json({ ok: true, database: result.rows[0]?.ok === 1 });
      } catch (error) {
        console.error("Healthcheck Hyperdrive:", error);
        return Response.json({ ok: false, error: String(error?.message || error) }, { status: 500 });
      }
    }

    if (url.pathname === "/api/login" && request.method === "POST") {
      try {
        return await loginDirect(request, workerEnv);
      } catch (error) {
        console.error("Falha inesperada no login:", error);
        return Response.json({ error: "Erro interno ao realizar login" }, { status: 500 });
      }
    }

    try {
      const state = await getRuntime(workerEnv);
      await ensureDatabase(state);
      return await state.expressHandler(request, workerEnv, ctx);
    } catch (error) {
      console.error("Falha ao inicializar o banco:", error);
      return new Response("Erro ao inicializar o banco de dados.", { status: 500 });
    }
  },
};
