import { handleAsNodeRequest, httpServerHandler } from "cloudflare:node";
import { createServer } from "node:http";

let runtimeState = globalThis.__APS_RANKING_RUNTIME || {
  loaded: false,
  app: null,
  initPromise: null,
  runtimePromise: null,
  server: null,
  nodeHandler: null,
};
globalThis.__APS_RANKING_RUNTIME = runtimeState;

function noStore(response) {
  const headers = new Headers(response.headers);
  headers.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
  headers.set("Pragma", "no-cache");
  headers.set("Expires", "0");
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

function base64url(value) {
  const bytes = typeof value === "string" ? new TextEncoder().encode(value) : new Uint8Array(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

async function signJwt(payload, secret) {
  const header = base64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const body = base64url(JSON.stringify({ ...payload, iat: Math.floor(Date.now() / 1000), exp: Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60 }));
  const data = `${header}.${body}`;
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(data));
  return `${data}.${base64url(signature)}`;
}

async function loginDirect(request, workerEnv) {
  const body = await request.json();
  const email = String(body?.email || "").trim().toLowerCase();
  const password = String(body?.password || "");
  if (!email || !password) return Response.json({ error: "Informe e-mail e senha" }, { status: 400 });

  const adminEmail = String(workerEnv.ADMIN_EMAIL || "admin@aps.local").trim().toLowerCase();
  const adminPassword = String(workerEnv.ADMIN_PASSWORD || "123456");
  const secret = workerEnv.JWT_SECRET || "TROQUE-ESTE-SEGREDO-EM-PRODUCAO";

  if (email === adminEmail && password === adminPassword) {
    try {
      const connectionString = workerEnv.HYPERDRIVE?.connectionString;
      if (connectionString) {
        const { Client } = await import("pg");
        const client = new Client({ connectionString });
        try {
          await client.connect();
          await client.query(`CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'consultant',
            active INTEGER NOT NULL DEFAULT 1,
            goal REAL NOT NULL DEFAULT 0,
            photo_data TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
          )`);
          let admin=(await client.query("SELECT id,name,email,role,goal,photo_data FROM users WHERE role='admin' ORDER BY id LIMIT 1")).rows[0];
          if(admin){
            admin=(await client.query(
              "UPDATE users SET name=$1,email=$2,active=1 WHERE id=$3 RETURNING id,name,email,role,goal,photo_data",
              ["Administrador",adminEmail,admin.id]
            )).rows[0];
          }else{
            admin=(await client.query(
              "INSERT INTO users (name,email,password_hash,role,goal,active) VALUES ($1,$2,$3,'admin',0,1) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,role='admin',active=1 RETURNING id,name,email,role,goal,photo_data",
              ["Administrador",adminEmail,adminPassword]
            )).rows[0];
          }
          const token=await signJwt({id:admin.id,name:admin.name,email:admin.email,role:"admin"},secret);
          return Response.json({token,user:{id:admin.id,name:admin.name,email:admin.email,role:"admin",goal:admin.goal||0,photo_data:admin.photo_data||null}});
        } finally { await client.end().catch(()=>{}); }
      }
    } catch(error) {
      console.error("Login admin: banco indisponível, usando fallback:",error);
    }
    const token=await signJwt({id:1,name:"Administrador",email:adminEmail,role:"admin"},secret);
    return Response.json({token,user:{id:1,name:"Administrador",email:adminEmail,role:"admin",goal:0,photo_data:null}});
  }

  const connectionString=workerEnv.HYPERDRIVE?.connectionString;
  if(!connectionString) return Response.json({error:"Banco de dados não conectado"},{status:500});
  const {Client}=await import("pg");
  const client=new Client({connectionString});
  try{
    await client.connect();
    const result=await client.query("SELECT id,name,email,password_hash,role,goal,photo_data FROM users WHERE email=$1 AND active=1 LIMIT 1",[email]);
    const user=result.rows[0];
    if(!user) return Response.json({error:"E-mail ou senha inválidos"},{status:401});
    const {default:bcrypt}=await import("bcryptjs");
    if(!(await bcrypt.compare(password,user.password_hash))) return Response.json({error:"E-mail ou senha inválidos"},{status:401});
    const token=await signJwt({id:user.id,name:user.name,email:user.email,role:user.role},secret);
    return Response.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role,goal:user.goal,photo_data:user.photo_data||null}});
  }catch(error){
    console.error("Falha no login via Hyperdrive:",error);
    return Response.json({error:`Login: ${String(error?.message||error)}`},{status:500});
  }finally{ await client.end().catch(()=>{}); }
}

async function getRuntime(workerEnv) {
  // O navegador abre vários endpoints da tela inicial em paralelo. Sem este
  // lock, duas requisições podem tentar criar o mesmo servidor Node na porta
  // 3000 ao mesmo tempo e uma delas cai em 503 (EADDRINUSE).
  if (runtimeState.loaded) return runtimeState;
  if (runtimeState.runtimePromise) return runtimeState.runtimePromise;
  runtimeState.runtimePromise = (async () => {
    if (!workerEnv.HYPERDRIVE?.connectionString) {
      throw new Error("HYPERDRIVE não configurado.");
    }

    globalThis.__CF_ENV = {
      CF_WORKER: "1",
      DATABASE_URL: workerEnv.HYPERDRIVE.connectionString,
      JWT_SECRET: workerEnv.JWT_SECRET,
      ADMIN_EMAIL: workerEnv.ADMIN_EMAIL,
      ADMIN_PASSWORD: workerEnv.ADMIN_PASSWORD,
      PRIZE_START_DATE: workerEnv.PRIZE_START_DATE,
      TEAM_B_PRIZE_START_DATE: workerEnv.TEAM_B_PRIZE_START_DATE,
      SUPERVISOR_ALL_TEAMS_START_DATE: workerEnv.SUPERVISOR_ALL_TEAMS_START_DATE,
    };

    const { app, init } = await import("./server.js");
    runtimeState.server = createServer(app);
    runtimeState.app = app;
    runtimeState.init = init;
    // O Cloudflare httpServerHandler gerencia o listen/roteamento do servidor.
    // Não chamamos server.listen() manualmente para evitar EADDRINUSE em cold start.
    runtimeState.nodeHandler = httpServerHandler(runtimeState.server);
    runtimeState.loaded = true;
    return runtimeState;
  })().catch(error => {
    runtimeState.runtimePromise = null;
    throw error;
  });
  return runtimeState.runtimePromise;
}

async function ensureDatabase(state) {
  if (state.initPromise) return state.initPromise;
  state.initPromise = (async () => {
    // O banco já foi criado e migrado nas publicações anteriores. Não rode
    // dezenas de CREATE/ALTER/UPDATE a cada novo isolamento do Worker.
    // Só executa a inicialização completa quando as tabelas-base realmente faltarem.
    const connectionString = globalThis.__CF_ENV?.DATABASE_URL;
    if (!connectionString) throw new Error("DATABASE_URL não configurada.");
    const { Client } = await import("pg");
    const client = new Client({ connectionString });
    try {
      await client.connect();
      const check = await client.query(`
        SELECT
          to_regclass('public.users') AS users_table,
          to_regclass('public.sales') AS sales_table,
          to_regclass('public.prize_rules') AS prize_rules_table,
          EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='users' AND column_name='team') AS users_team,
          EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='sales' AND column_name='sale_date') AS sales_sale_date,
          EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='sales' AND column_name='gross_amount') AS sales_gross_amount,
          EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='prize_rules' AND column_name='min_installments') AS prize_rules_min_installments
      `);
      const row = check.rows[0] || {};
      if (
        row.users_table && row.sales_table && row.prize_rules_table &&
        row.users_team && row.sales_sale_date && row.sales_gross_amount &&
        row.prize_rules_min_installments
      ) return;
    } finally {
      await client.end().catch(() => {});
    }
    await state.init();
  })().catch((error) => {
    state.initPromise = null;
    throw error;
  });
  return state.initPromise;
}

export default {
  async fetch(request, workerEnv, ctx) {
    const url = new URL(request.url);

    if (!url.pathname.startsWith("/api/")) {
      return workerEnv.ASSETS.fetch(request);
    }

    if (url.pathname === "/api/health" && request.method === "GET") {
      const connectionString = workerEnv.HYPERDRIVE?.connectionString;
      if (!connectionString) return noStore(Response.json({ ok: false, error: "HYPERDRIVE não configurado" }, { status: 500 }));
      try {
        const { Client } = await import("pg");
        const client = new Client({ connectionString });
        await client.connect();
        const result = await client.query("SELECT 1 AS ok");
        await client.end().catch(() => {});
        return noStore(Response.json({ ok: true, database: result.rows[0]?.ok === 1 }));
      } catch (error) {
        console.error("Healthcheck Hyperdrive:", error);
        return noStore(Response.json({ ok: false, error: String(error?.message || error) }, { status: 500 }));
      }
    }

    if (url.pathname === "/api/login" && request.method === "POST") {
      try {
        return noStore(await loginDirect(request, workerEnv));
      } catch (error) {
        console.error("Falha inesperada no login:", error);
        return Response.json({ error: "Erro interno ao realizar login" }, { status: 500 });
      }
    }

    try {
      const state = await getRuntime(workerEnv);
      // O código Node do servidor não executa init() automaticamente no Worker.
      // Garante o schema/migrações antes de atender a primeira API, sem apagar dados.
      await ensureDatabase(state);
      return noStore(await state.nodeHandler.fetch(request, workerEnv, ctx));
    } catch (error) {
      console.error("Falha ao inicializar o banco:", error);
      const message = String(error?.message || error || "Erro desconhecido");
      return Response.json(
        { error: "Erro ao inicializar o banco de dados", detail: message.slice(0, 500) },
        { status: 503 }
      );
    }
  },
};